name: build
on:
  pull_request:
  push:
    branches: [ main ]
defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-latest
    steps:
      - name: deps
        uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: humble
      - name: install_clang
        run: sudo apt update && sudo apt install -y clang clang-tools lld
      - name: build
        uses: ros-tooling/action-ros-ci@v0.2
        env:
          CC: clang
          CXX: clang++
        with:
          target-ros2-distro: humble
          # build all packages listed in the meta package
          package-name: |
            nirmitsu_ros2_flowgraph
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc","lld"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
